global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9114']

  # - job_name: 'jellyfin'
  #   static_configs:
  #     - targets: ['jellyfin_exporter:8080']

  - job_name: 'ebpf'
    static_configs:
      - targets: ['ebpf_exporter:9435'] 