# Gandi.net API Credentials for Certbot DNS Challenge
# API documentation: https://api.gandi.net/docs/authentication/
# Test a token: curl -H "Authorization: Bearer <TOKEN>" https://id.gandi.net/tokeninfo

dns_gandi_api_key = a3d9c466bd09faff680c0022d501d358a0fa3066 